source 'https://rubygems.org'

ruby '~> 3.4.0'

gem 'bigdecimal'
gem 'commonmarker'
gem 'mysql2'
gem 'nokogiri'
gem 'redcarpet'

group :development do
  gem 'rubocop'
end

group :test do
  gem 'rspec'
end
